environment:

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    - PYTHON: "C:\\Python37-x64"

install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt -r dev_requirements.txt"

build_script:
  - ps: Start-FileDownload 'https://raw.githubusercontent.com/Drakkar-Software/OctoBot/dev/interfaces/web/static/favicon.ico'
  - "echo f | xcopy /f /y favicon.ico interfaces\\web\\static\\favicon.ico"
  - "rd /s /q launcher\\app  launcher\\tools"
  - "del /q launcher\\*.py launcher\\static\\* launcher\\templates\\*"
  - "%PYTHON%\\Scripts\\pyinstaller.exe bin/launcher.spec"
  - "echo f | xcopy /f /y dist\\launcher.exe dist\\launcher_windows.exe"
  - "powershell get-filehash -algorithm sha1 dist\\launcher_windows.exe"

test_script:
  - "%PYTHON%\\python.exe -m pytest"

artifacts:
  - path: dist/launcher_windows.exe
    name: launcher_windows.exe

deploy:
  - provider: Environment
    name: GITHUB_RELEASE_OCTOBOT_LAUNCHER
    draft: false
    prerelease: false
    artifact: launcher_windows.exe
    on:
      branch: master
      APPVEYOR_REPO_TAG: true
